### ISSUE TITLE
Recommend changing environment to "client"

### ISSUE THREAD

**Issue by Linguardium** [Lucaslah/WeatherChanger#2]
https://github.com/Lucaslah/WeatherChanger/blob/993df4b93d3d7454bd156ab84004967cab802cbd/src/main/resources/fabric.mod.json#L21

Since this mod is client only, i recommend changing the environment to client to prevent servers from attempting to load the mod (and thus the common entrypoint ) if someone drops it in their server mods list

**Comment by Lucaslah** [comment]
Hi, thanks for pointing this out, unfortunately I am not able to publish any updates at the moment,
Ill change this in the next release.

**Comment by Lucaslah** [comment]
Fixed in #3
